### ISSUE TITLE
fix game quit

### ISSUE THREAD

**Issue by trosh** [Brian-Catcow-B/tetrisn-t#44]
the “down + cw + ccw + esc” action doesn't work for me (also it's super awkward!)

I suppose a simple resume/quit selection screen in the pause menu would be better

**Comment by Brian-Catcow-B** [comment]
Yeah I found out that some older keyboards (and laptop keyboards in general) tend to have a firmware limit on how many buttons can be pressed at once, which is what causes that to be a problem. For now I'll just change it to be "down + esc" so that it is a lot easier to do (or possible in the first place) but also can't really happen on accident.

**Comment by Brian-Catcow-B** [comment]
merged to dev
