### ISSUE TITLE
piece colour (before snap)

### ISSUE THREAD

**Issue by trosh** [Brian-Catcow-B/tetrisn-t#47]
It would be helpful if pieces had specific colours, to help with lookahead. The colourscheme can be nintendo, tengen, or whatever you want, I'm sure you can find a logic behind that choice.

However, I think it's nice that the board is a single colour (like in Tengen I think), because it helps thinking about the actual state of the board, and not about the “history” of how it came to be. (I hope this makes sense!) So I'm recommending specific colours only before pieces snap.

**Comment by trosh** [comment]
btw the colour change might suffice to provide snap feedback to solve issue #46

**Comment by Brian-Catcow-B** [comment]
highlights added around active piece tiles; merged into dev (and master because git still confuses me sometimes)

once I fix some of the other things I'll make a v0.1.1 tag

**Comment by trosh** [comment]
the highlights are alright, but the idea behind colour is to help reckon lookahead with only peripheral vision

**Comment by trosh** [comment]
for example, Tengen Tetris has a nice colour scheme but locked pieces are all the same colour https://www.youtube.com/watch?v=GcXrNKfcr3M

**Comment by Brian-Catcow-B** [comment]
Okay, so the reason I won't be implementing this is that tetrisnt is primarily a multiplayer coop game, but with the option to play singeplayer. I will probably eventually add different piece colors for singleplayer mode, but I think it's more important to be able to tell which piece is yours by the color than to be able to tell which type of piece is next without glancing up at it.

So basically, I'll eventually implement the 3-color system that 1989 NEStris has when it comes to singleplayer, but multiplayer the colors will be based on which player has the piece. This was actually done in the `rotatris-...` branches, which is an interesting different mode I experimented with for Game Jam this year, but idk exactly how/if I'll implement the rotatris mode into tetrisnt, since there'd have to be a bit of overhaul in the menus, and it's currently just singleplayer for multiple reasons. `git checkout rotatris-only && cargo run --release` to try it out
